### PR TITLE
Data visualisation

### PR DESCRIPTION
**Pull request by Mridul20**
#7 
Generated the OHLC chart using mplfinance.

### CODE REVIEW

**Comment by TamoghnoBhattacharya** [comment]
Add the requirements.txt file in the 'Data Science' directory. It should be common for the entire project.

**Comment by divyanshrai655** [comment]
> Add the requirements.txt file in the 'Data Science' directory. It should be common for the entire project.

Like in for all three in one @TamoghnoBhattacharya right?

**Comment by TamoghnoBhattacharya** [comment]
> > Add the requirements.txt file in the 'Data Science' directory. It should be common for the entire project.
> 
> Like in for all three in one @TamoghnoBhattacharya right?

No let the other 2 issues remain open. What I meant was there should be only 1 requirements.txt file for entire project in the same directory as the readme file, not multiple for different roll numbers.

**Comment by divyanshrai655** [comment]
> No let the other 2 issues remain open. What I meant was there should be only 1 requirements.txt file for entire project in the same directory as the readme file, not multiple for different roll numbers.

Got it

**Comment by Mridul20** [comment]
@TamoghnoBhattacharya  chaged the location of requirements.txt in the "Data Science " folder.

**Comment by divyanshrai655** [comment]
@Mridul20 it seems you haven't seen the details mentioned in the readme which stated "Write a script to take any arbitrary dataset with the format previously given, and return a chart showing the HLOC chart of the data".

**Comment by TamoghnoBhattacharya** [comment]
@Mridul20 This issue will use dataset created in the previous issue data collection which isn't solved yet. So try and solve that first and then open a PR for this, or wait till someone solves it and use his/her dataset.

**Comment by Mridul20** [comment]
@TamoghnoBhattacharya  OK.

**Pull request closed without merging**
