### PR TITLE
Added code to retrieve stock data (yfinance)

### PR DESCRIPTION
**Pull request by aarpit1010**
#5 
Added code snippet to retrieve stock data using yfinance for MSFT ticker.

### CODE REVIEW

**Comment by divyanshrai655** [comment]
Though this code seems perfect to me, yet I recommend you to make this as a function that process and returns a CSV that would be like solving two issues #6 and #5 with one PR. @aarpit1010

**Comment by aarpit1010** [comment]
So, basically the function should take ticker as the argument and retrieve data for that ticker and return its CSV file..
pls. verify whether this is what is supposed to be done..
@Lazy-Leopard

**Comment by aarpit1010** [comment]
@Lazy-Leopard @TamoghnoBhattacharya 
I have updated the code with the required function, pls. review

**Comment by divyanshrai655** [comment]
@aarpit1010 sorry for late reply, your function runs correctly for different tickers (update every minute the) but returns the overall change in one minute not the HLOC data, kindly check out other functions or you may use different modules if required or maybe some other approach using the same function.

Edit - Maybe this is due to frequency of data getting updated for various tickers, like MSFT is giving all the values for HLOC different for 1m time interval whereas ETH-INR gives the value have all HLOC values. Few of the ticker codes are not known or available, maybe extracted using APIs.I think this is good to go, @europe-asia-america confirm this at the earliest😅 .

**Comment by aarpit1010** [comment]
Also, the function gives an error `AttributeError: Can only use .dt accessor with datetimelike values` for NIFTY 50 only, maybe because it has different datetime format..
Bcz for all others it works perfectly fine...
@Lazy-Leopard

**Pull request merged**
