### PR TITLE
Retrieved stock data

### PR DESCRIPTION
**Pull request by Mridul20**
#5 
Retrived intraday stock data using yfinance for the given dates as 1m interval.

### CODE REVIEW

**Comment by europe-asia-america** [comment]
Why did you name the csv you are saving as "Intradata.py"? That can cause confusion to new users. Change that.

**Comment by Mridul20** [comment]
Ok.

**Comment by Mridul20** [comment]
@europe-asia-america  changed the format of file to .csv . Please check.

**Comment by europe-asia-america** [comment]
Add a `requirements.txt` file containing all the pip packages that need to be installed to run this code.

I recommend using `pipreqs` or another program to automatically make the file.


EDIT: For any issue where you use a new package, update `requirements.txt` too in your PR.

**Comment by Mridul20** [comment]
Ok. Will do the same

**Comment by Mridul20** [comment]
@europe-asia-america  Added requirements.txt file. Please check and verify.

**Pull request closed without merging**
