### PR TITLE
Added 2-column Matrix Metadata DataFrame

### PR DESCRIPTION
**Pull request by aarpit1010**
#2
Prepared the 2-column Matrix having movie title and metadata as columns.
Metadata consists of genre column (movies.csv) & tag column (tags.csv).

### CODE REVIEW

**Comment by TamoghnoBhattacharya** [comment]
@aarpit1010 Code's working great, just add a requirements.txt file in the same directory as the readme file mentioning all the packages or modules required to run the code.

**Comment by aarpit1010** [comment]
@TamoghnoBhattacharya  I have added the `requirements.txt` file stating the versions that are required by the python libraries.

**Comment by TamoghnoBhattacharya** [comment]
> @TamoghnoBhattacharya  I have added the `requirements.txt` file stating the versions that are required by the python libraries.

Keep it in the same directory as the readme file, not in your roll number folder. It has to be accessed and edited by everyone.

**Comment by aarpit1010** [comment]
@TamoghnoBhattacharya made the required changes

**Comment by TamoghnoBhattacharya** [comment]
@Lazy-Leopard Bhai merge kar de yaar mai sab kuch bandh karke sone aa gaya hu 🤣.

**Pull request merged**
