### PR TITLE
User Movie Rating Matrix

### PR DESCRIPTION
**Pull request by JLodha**
This PR is for the Issue Number #3 

Issue : Use the ratings.csv file to generate a 2D numpy array whose (i,j)th entry is the rating given by i'th user to j'th movie.

Solution : I used pandas to import the ratings.csv file as a data frame in the working python file. Later separated out the required fields (userId, movieId, rating). Finally used the "Pandas Pivot" to convert it into required matrix as per the issue.

Screenshot : 
image

### CODE REVIEW

**Comment by TamoghnoBhattacharya** [comment]
Rename your py file to something else, like rating_matrix or something, and what is my code doing there? Delete all those lines.

**Comment by JLodha** [comment]
> Rename your py file to something else, like rating_matrix or something, and what is my code doing there? Delete all those lines.

Done.
Please have a look.

**Comment by TamoghnoBhattacharya** [comment]
Congrats! For further PRs, do not mention issue, solution, screenshot etc. Just mention like 'user rating movie matrix created'. We'll see the rest.

**Comment by divyanshrai655** [comment]
> Congrats! For further PRs, do not mention issue, solution, screenshot etc. Just mention like 'user rating movie matrix created'. We'll see the rest.

Though I think showing the output screenshot is a good idea and must be implemented else where too.

**Comment by TamoghnoBhattacharya** [comment]
> > Congrats! For further PRs, do not mention issue, solution, screenshot etc. Just mention like 'user rating movie matrix created'. We'll see the rest.
> 
> Though I think showing the output screenshot is a good idea and must be implemented else where too.

Agreed.

**Pull request merged**
